### ISSUE TITLE
options to display a points.geojson file in leaflet map template?

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets-dev#16]
@ilyankou  - Question from @aperez773. He also wants to display a points GeoJSON file of 1000+ trees in his Leaflet map template for Hartford Climate Stewardship Council. I uploaded the file here (see geometry/knox-trees.geojson). Your template can handle polylines.geojson and polygons.geojson, but we have always handled points directly in the Google Sheet, not as a points.geojson file.

Options:
1) I can help him to convert the lat-lng from the geojson points file into the Google Spreadsheet, but it would be 1000+ rows
 
2) You and I could help him to modify the underlying js code to display geojson points

Please think about options and let's discuss on Wednesday

**Comment by aperez773** [comment]
Hi Jack,

I looked at the comments, it seems Ilya was able to add the trees into the map template. I was a bit confused with the steps, but I was able to follow through of most of the process.

Alex


On Apr 9, 2017, at 9:56 AM, Jack Dougherty <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #16<https://github.com/JackDougherty/leaflet-maps-with-google-sheets-dev/issues/16> via #19<https://github.com/JackDougherty/leaflet-maps-with-google-sheets-dev/pull/19>.

**Comment by JackDougherty** [comment]
Hi @aperez773  -- Ilya has made changes to the dev (or testing) repo, which uses a different Google Sheet than the one that is linked to our master repo. But I need to speak with Ilya before we officially merge these changes into the master repo. Your options:
1) live on the edge and fork a copy of the dev repo and dev Google Sheet 
or
2) wait a couple of days until Ilya and I officially release it on the main repo

**Comment by aperez773** [comment]
Hi Jack,

For now, Ill wait until you and Ilya finalize it.

-Alex

On Apr 9, 2017, at 7:20 PM, Jack Dougherty <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @aperez773<https://github.com/aperez773> -- Ilya has made changes to the dev (or testing) repo, which uses a different Google Sheet than the one that is linked to our master repo. But I need to speak with Ilya before we officially merge these changes into the master repo. Your options:

  1.  live on the edge and fork a copy of the dev repo and dev Google Sheet
or
  2.  wait a couple of days until Ilya and I officially release it on the main repo
