### ISSUE TITLE
ways to simplify Options and Polygons

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets-dev#21]
@ilyankou - let's discuss ways to simplify some Options and Polygons setting during our next Skype call, in order to help users understand how to use the wonderful new settings you've created

First, I recommend that we remove Options row 17 (Display Polygons Simultaneously) and hard-code this as "true" in script.js. When users create multiple Polygons tabs, they probably want to show all of the legends simultaneously (but not necessarily the polygon data -- see below).

As a result, we could remove Polygons row 3 (Polygon Legend Title, which only appears when Option row 17 = false). Instead, we could rename Polygons row 5 (Polygon GeoJSON Name, which confuses users) to Polygon Legend Title, and move it up into row 3.

Also, we could create a new row between Polygons 10 and 11 titled "Show Polygon Data on Start" with on/off settings, and the default = on. When set to off, the polygon legend would appear on the screen, but the initial setting is off, so no polygons would appear. (This makes sense in cases like Alex's Hartford Climate map, where so many polygons appear on start-up that it's hard to see.)

Second, I recommend that we remove Options row 18 (Display Commas in Numbers) and hard-code this as "true" in script.js for now. Later, we could revisit this to create a Localization control for how to display large numbers: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

**Comment by ilyankou** [comment]
Jack, I agree with most of your ideas and I will try to implement some before our Skype talk this week. What do you think of this legend layout?

![screen shot 2017-04-10 at 14 53 23](https://cloud.githubusercontent.com/assets/10443203/24851384/9ccbca32-1dfd-11e7-85e7-233259439e02.png)
