### ISSUE TITLE
feature request: Start map with selected items "off" in Points tab 

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets-dev#26]
@ilyankou -- Several students have requested the ability to start up their maps with selected items "off" by default in the Points tab. 

Examples: 
https://aperez773.github.io/climatemap2/  (wants users to turn on selected points)
and
https://jordanpolitz.github.io/leaflet-maps-with-google-sheets/   (displays too many points at once)

Unless you have already thought of a better solution, my recommendation is to insert a Start column into the Points tab, with on/off setting, to allow map creators to designate precisely which items to display on startup.

**Comment by ilyankou** [comment]
@JackDougherty this is the best solution I can think of, too. Similarly to point-marker-icon, for each category it will get the first value of `Display on Start`. If it's `on`, will display that layer on start. That is, all points on a layer will be either `on` or `off`.
