### ISSUE TITLE
bug: points legend order determined by most recently-edited tabs

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets-dev#32]
@ilyankou - the legend order appears to be determined by the most recently-edited tabs, not the sequence of the tabs in the Google Sheet

![leaflet_maps_with_google_sheets_and_leaflet_maps_with_google_sheets_development_-_google_sheets_and_inbox__127_messages_](https://cloud.githubusercontent.com/assets/649719/25336577/2defe426-28c6-11e7-982b-07bc871e1053.png)

**Comment by ilyankou** [comment]
Haha that's interesting – I will look into it.

@JackDougherty This is somewhat tricky. Logically it works correctly. `mapData.foundSheetNames` (which I use to rearrange the legends) has tab names in order left to right, not by the age of the tabs. Whenever I refresh the map, the order of legends changes. Every other time the order is correct, but it interchanges with some random order (which also stays consistent). Maybe it has to do with cache?
