### ISSUE TITLE
It's not loading.

### ISSUE THREAD

**Issue by opedromandrade** [JackDougherty/leaflet-maps-with-google-sheets-dev#34]
Wanting to update a small project i've had made in the past, I've noticed that the map just keeps on loading but it doesn't load completely. Any way to fix this?

Thanks.

**Comment by JackDougherty** [comment]
You should use our public version of this Leaflet template, not this old development version.
See pinned Leaflet templates at https://github.com/HandsOnDataViz
See open-access book with tutorials at https://handsondataviz.org
