### ISSUE TITLE
please check Search Radius

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-maps-with-google-sheets-dev#9]
@ilyankou - in Options, we list Search Radius, to display results of a Mapzen search. Is this still working as you intended? I cannot tell, and am wondering if I might have broken it when upgrading Mapzen this weekend.

**Comment by ilyankou** [comment]
I am using the 'circle' property of L.control.geocoder, which is no longer in specs (https://github.com/mapzen/leaflet-geocoder). I will look into this

**Comment by JackDougherty** [comment]
Ilya will look into older commits to see if he can find the old version of this code he wrote. If so, he will add to our code package and possibly submit to Mapzen
